// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products_and_categories.Models;

#nullable disable

namespace Products_and_categories.Migrations
{
    [DbContext(typeof(Products_and_categoriesContext))]
    partial class Products_and_categoriesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("catProductsProductId")
                        .HasColumnType("int");

                    b.Property<int>("prodCategoriesCategoryId")
                        .HasColumnType("int");

                    b.HasKey("catProductsProductId", "prodCategoriesCategoryId");

                    b.HasIndex("prodCategoriesCategoryId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Products_and_categories.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Products_and_categories.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Products_and_categories.Models.ProductToCategory", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AssociationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Products_and_categories.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("catProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Products_and_categories.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("prodCategoriesCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Products_and_categories.Models.ProductToCategory", b =>
                {
                    b.HasOne("Products_and_categories.Models.Category", "CategoryAss")
                        .WithMany("ProductAssociations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Products_and_categories.Models.Product", "ProductAss")
                        .WithMany("CategoryAssociations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryAss");

                    b.Navigation("ProductAss");
                });

            modelBuilder.Entity("Products_and_categories.Models.Category", b =>
                {
                    b.Navigation("ProductAssociations");
                });

            modelBuilder.Entity("Products_and_categories.Models.Product", b =>
                {
                    b.Navigation("CategoryAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
